version: '3'
name: Chat
services:
  postgres_db:
    image: postgres:13-alpine
    container_name: chat_postgres
    environment:
      POSTGRES_USER: alusus
      POSTGRES_PASSWORD: alusus
    ports:
      - 5432:5432
